name: ci
on: [pull_request, push]
jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        go: ['1.13.x']
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build
      run: go build ./...
